// Planet Data
export const PLANETS = [
    {
        name: 'Mercury',
        radius: 0.5,
        distance: 30,
        speed: 1,
        color: 'gray',
        details: 'The smallest and fastest planet in our solar system, closest to the Sun.',
        icon: '/planets/mercury.png',
    },
    {
        name: 'Venus',
        radius: 0.9,
        distance: 50,
        speed: 0.5,
        color: 'orange',
        details: 'The second planet from the Sun, known for its extreme heat and thick atmosphere.',
        icon: '/planets/venus.png',
    },
    {
        name: 'Earth',
        radius: 1,
        distance: 80,
        speed: 0.3,
        color: 'blue',
        details: 'Our home planet, the only known planet to support life.',
        icon: '/planets/earth.png',
    },
    {
        name: 'Mars',
        radius: 0.8,
        distance: 100,
        speed: 0.25,
        color: 'red',
        details: 'The Red Planet, known for its iron oxide-rich soil.',
        icon: '/planets/mars.png',
    },
    {
        name: 'Jupiter',
        radius: 4,
        distance: 150,
        speed: 0.1,
        details: 'The largest planet in our solar system, a gas giant with a Great Red Spot.',
        icon: '/planets/jupiter.png',
    },
    {
        name: 'Saturn',
        radius: 3.5,
        distance: 200,
        speed: 0.09,
        color: 'goldenrod',
        hasRings: true,
        details: 'Known for its prominent ring system, Saturn is the second-largest planet.',
        icon: '/planets/saturn.png',
    },
    {
        name: 'Uranus',
        radius: 3,
        distance: 250,
        speed: 0.08,
        color: 'lightblue',
        details: 'The planet with a unique sideways rotation and faint ring system.',
        icon: '/planets/uranus.png',
    },
    {
        name: 'Neptune',
        radius: 3,
        distance: 300,
        speed: 0.07,
        color: 'blue',
        details: 'The most distant planet from the Sun, known for its deep blue color.',
        icon: '/planets/neptune.png',
    },
    {
        name: 'Pluto',
        radius: 0.4,
        distance: 350,
        speed: 0.05,
        color: 'white',
        details: 'Once considered the ninth planet, Pluto is now classified as a dwarf planet.',
        icon: '/planets/pluto.png',
    },
];
