/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Moon.glb -o src/components/Moon.jsx -k -K -r public 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Moon(props: any) {
    const { nodes, materials }: any = useGLTF('/models/Moon.glb');
    return (
        <group {...props} dispose={null}>
            <mesh name='moon' geometry={nodes.moon.geometry} material={materials['moon.002']} />
        </group>
    );
}
useGLTF.preload('/models/Moon.glb');
